version: "3.2"

services:
  mysql:
    container_name: mysql
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: JokesAPI
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    container_name: redis
    image: redis:5
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  backend:
    container_name: backend
    image: backend:latest
    restart: always
    command : bash -c "python manage.py migrate && gunicorn backend.wsgi -w 4 -b 0.0.0.0:8000"
    env_file:
      - ./backend/.env
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
  frontend:
    container_name: frontend
    image: frontend:latest
    restart: always
    env_file:
      - ./frontend/.env
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - backend
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend

volumes:
  mysql_data:
  redis_data:
