# Generated by Django 3.2.8 on 2021-10-20 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
                ('body', models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(1000)])),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
